apiVersion: v1
kind: Pod
metadata:
  name: wangzg-gemma-1
  labels:
    workstream: embodiment
spec:
  serviceAccountName: hyperpod-node-iam
  containers:
    - name: wangzg-gemma-1
      image: 763104351884.dkr.ecr.eu-west-2.amazonaws.com/pytorch-training:2.8.0-gpu-py312-cu129-ubuntu22.04-ec2
      command: ["sleep", "infinity"]
      resources:
        limits:
          nvidia.com/gpu: 1
        requests:
          nvidia.com/gpu: 1
  #########################
      volumeMounts:
      - name: fsx-volume
        mountPath: /fsx/shared
      - name: fsx-volume
        mountPath: /fsx/users/wangzg
        subPath: users/wangzg
      # - name: fsx-volume
      #   mountPath: /root
      #   subPath: users/wangzg
      # mount a dedicated subdir for VS Code server
      - name: fsx-volume
        mountPath: /root/.vscode-server
        subPath: users/wangzg/.vscode-server
      - name: shmem
        mountPath: /dev/shm


  volumes:
  - name: fsx-volume
    persistentVolumeClaim:
      claimName: cairo-fsx-lustre-claim
  - name: shmem
    hostPath:
      path: /dev/shm
  restartPolicy: Never